name: Build 100ask project docs

on:
  push:
    branches:    
      - master
env:
  EM_VERSION: 2.0.4
  EM_CACHE_FOLDER: 'emsdk-cache'
jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        # Cache the Python package environment, excluding pip and setuptools installed by setup-python
        path: |
          ~/.cache/pip
          ${{ env.pythonLocation }}/bin/*
          ${{ env.pythonLocation }}/include
          ${{ env.pythonLocation }}/lib/python*/site-packages/*
          !${{ env.pythonLocation }}/bin/pip*
          !${{ env.pythonLocation }}/lib/python*/site-packages/pip*
          !${{ env.pythonLocation }}/lib/python*/site-packages/setuptools*
        key: ${{ env.pythonLocation }}-${{ hashFiles('docs/requirements.txt') }}
    #- name: Install requirements
    #  run: |
    #    pip install -r docs/requirements.txt
    # Example of using a custom build-command.
    # Building HTML.
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt-get update -y && pip install sphinx_rtd_theme recommonmark sphinx_markdown_tables sphinx_sitemap"
        build-command: "sphinx-build -b html . _build"
        #build-command: "make html"
        docs-folder: "docs/"

    # Publish built docs to gh-pages branch.
    # ===============================
    - name: Commit documentation changes
      run: |
        #git clone https://${{secrets.GITEE_USERNAME}}:${{secrets.GITEE_PASSWD}}@gitee.com/weidongshan/InformationDownloadCenter.git --branch master --single-branch master
        git clone https://${{secrets.CODING_USERNAME}}:${{secrets.CODING_PASSWD}}@e.coding.net/weidongshan/sphinx_docs/100ask_data_download_center.git --branch master --single-branch master
        cp -r docs/_build/* master/
        cd master
        touch .nojekyll
        git config --local user.email "baiwenwang@100ask.com"
        git config --local user.name "www.100ask.org"
        git add .
        git commit -m "Update documentation" -a || true
        git push origin master
        # The above command will fail if no changes were present, so we ignore
        # that.B_TOKEN }}
    - name: executing remote ssh command using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: root
        key: ${{ secrets.SSH_ID_RSA }}
        port: 22
        script: |
          ls -al
          cd /home/100ask_data_download_center  && git pull
