name: Build 100ask project docs

on:
  push:
    branches:    
      - master
env:
  EM_VERSION: 2.0.4
  EM_CACHE_FOLDER: 'emsdk-cache'
jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.19
    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        # Cache the Python package environment, excluding pip and setuptools installed by setup-python
        path: |
          ~/.cache/pip
          ${{ env.pythonLocation }}/bin/*
          ${{ env.pythonLocation }}/include
          ${{ env.pythonLocation }}/lib/python*/site-packages/*
          !${{ env.pythonLocation }}/bin/pip*
          !${{ env.pythonLocation }}/lib/python*/site-packages/pip*
          !${{ env.pythonLocation }}/lib/python*/site-packages/setuptools*
        key: ${{ env.pythonLocation }}-${{ hashFiles('docs/requirements.txt') }}
    #- name: Install requirements
    #  run: |
    #    pip install -r docs/requirements.txt
    # Example of using a custom build-command.
    # Building HTML.
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt-get update -y && pip install sphinx_rtd_theme recommonmark sphinx_markdown_tables sphinx_sitemap"
        build-command: "sphinx-build -b html . _build"
        #build-command: "make html"
        docs-folder: "docs/"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/_build/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.CI_TOKEN }}
        publish_dir: docs/_build/
